### ISSUE TITLE
Error on Windows?

### ISSUE THREAD

**Issue by rchanou** [petehunt/webpack-require#2]
I'm using Windows 8.1. When trying to use it or run the test script, I get something like:

```
Started
Error: Invalid path '\bundle.js'
    at pathToArray (c:\REDACTED\webpack-require\node_modules\memory-fs\lib\MemoryFileSystem.js:27:38)
    at MemoryFileSystem.readFileSync (c:\REDACTED\webpack-require\node_modules\memory-fs\lib\MemoryFileSystem.js:75:13)
    at c:\REDACTED\webpack-require\lib\webpackRequire.js:47:19
    at Tapable.<anonymous> (c:\REDACTED\webpack-require\node_modules\webpack\lib\Compiler.js:193:14)
    at Tapable.emitRecords (c:\REDACTED\webpack-require\node_modules\webpack\lib\Compiler.js:281:37)
    at Tapable.<anonymous> (c:\REDACTED\webpack-require\node_modules\webpack\lib\Compiler.js:186:11)
    at c:\REDACTED\webpack-require\node_modules\webpack\lib\Compiler.js:274:11
    at Tapable.applyPluginsAsync (c:\REDACTED\webpack-require\node_modules\tapable\lib\Tapable.js:60:69)
    at Tapable.afterEmit (c:\REDACTED\webpack-require\node_modules\webpack\lib\Compiler.js:271:8)
    at Tapable.<anonymous> (c:\REDACTED\webpack-require\node_modules\webpack\lib\Compiler.js:266:14)
F

Failures:
1) webpackRequire works
  Message:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
  Stack:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
        at Timer.listOnTimeout (timers.js:119:15)

1 spec, 1 failure
Finished in 5.006 seconds
npm ERR! Test failed.  See above for more details.
```

Could be something else, but this was my first thought.

**Comment by rchanou** [comment]
FYI, it works when I change line 47 in webpackRequire.js from...

```
var data = fs.readFileSync(path.join(compiler.outputPath, 'bundle.js'), 'utf8');
```

...to...

```
var data = fs.readFileSync('/bundle.js', 'utf8');
```

BTW, you know you're my hero, right? Thanks for being awesome.

**Comment by petehunt** [comment]
thanks for the kind words @rchanou. want to send a PR?
